//! Generated RVA mappings for a single executable.

// DO NOT EDIT THIS FILE DIRECTLY.

use super::RvaBundle;

/// The RVAs for this executable.
///
/// These are populated from `mapper-profile.toml` in the root of this package
/// using `tools/binary-generator`.
pub const RVAS: RvaBundle = RvaBundle {
    cs_ez_draw_draw_line: 0x264fdb0,
    cs_ez_draw_draw_capsule: 0x2c0ca0,
    cs_ez_draw_draw_sphere: 0x1d26b0,
    cs_ez_draw_draw_wedge: 0x264f6b0,
    cs_ez_draw_draw_triangle: 0x264fb00,
    cs_ez_draw_draw_dodecadron: 0x2dd000,
    initialize_spawn_geometry_request: 0x1db670,
    spawn_geometry: 0x6a5150,
    cs_phys_world_cast_ray: 0xc707b0,
    cs_bullet_manager_spawn_bullet: 0x3a2dd0,
    chr_ins_apply_speffect: 0x3e8cf0,
    chr_ins_remove_speffect: 0x3ee1b0,
    cs_action_button_man_execute_action_button: 0xa62ff0,
    cs_menu_man_imp_display_status_message: 0x766460,
    global_hinstance: 0x3d85688,
    register_task: 0xeb2000,
};
