//! Generated RVA mappings for a single executable.

// DO NOT EDIT THIS FILE DIRECTLY.

use super::RvaBundle;

/// The RVAs for this executable.
///
/// These are populated from `mapper-profile.toml` in the root of this package
/// using `tools/binary-generator`.
pub const RVAS: RvaBundle = RvaBundle {
    chr_ins_apply_speffect: 0x3e8be0,
    chr_ins_remove_speffect: 0x3ee0b0,
    cs_action_button_man_execute_action_button: 0xa62ee0,
    cs_bullet_manager_spawn_bullet: 0x3a2ca0,
    cs_ez_draw_draw_capsule: 0x2c0b90,
    cs_ez_draw_draw_dodecadron: 0x2dcef0,
    cs_ez_draw_draw_line: 0x264fcf0,
    cs_ez_draw_draw_sphere: 0x1d2630,
    cs_ez_draw_draw_triangle: 0x264fa40,
    cs_ez_draw_draw_wedge: 0x264f5f0,
    cs_menu_man_imp_display_status_message: 0x766370,
    cs_phys_world_cast_ray: 0xc706c0,
    global_hinstance: 0x3d85688,
    initialize_spawn_geometry_request: 0x1db5f0,
    multiplay_properties: 0x3b11230,
    register_task: 0xeb1f40,
    spawn_geometry: 0x6a5080,
};
