//! Generated RVA mappings for a single executable.

// DO NOT EDIT THIS FILE DIRECTLY.

use super::RvaBundle;

/// The RVAs for this executable.
///
/// These are populated from `mapper-profile.toml` in the root of this package
/// using `tools/binary-generator`.
pub const RVAS: RvaBundle = RvaBundle {
    game_data_man_ptr: 0x47572b8,
    gesture_data_store: 0x45672e0,
    lua_event_man_give_item_directly: 0x46cad0,
    lua_event_man_remove_item: 0x473bd0,
    map_item_man_grant_item: 0x7c4080,
    map_item_man_ptr: 0x4769240,
    register_task: 0xf0fa50,
};
