//! Generated RVA mappings for a single executable.

// DO NOT EDIT THIS FILE DIRECTLY.

use super::RvaBundle;

/// The RVAs for this executable.
///
/// These are populated from `mapper-profile.toml` in the root of this package
/// using `tools/binary-generator`.
pub const RVAS: RvaBundle = RvaBundle {
    app_menu_new_menu_system_ptr: 0x3d8a140,
    component_proxy_vmt: 0x2aa3738,
    dlbuffered_input_stream_vmt: 0x2dd84d0,
    dlpseudo_async_input_stream_vmt: 0x2de30d8,
    fd4param_res_cap_vmt: 0x3280eb0,
    fd4res_cap_vmt: 0x3284610,
    game_data_man_ptr: 0x3d5aac0,
    global_hinstance: 0x3e9edb8,
    lua_event_man_remove_item: 0x67b230,
    map_item_man_grant_item: 0x91c970,
    map_item_man_ptr: 0x3d6cdc0,
    menu_window_vmt: 0x2aa6308,
    param_res_cap_vmt: 0x2b976b8,
    register_task: 0x11df640,
    scene_obj_proxy_vmt: 0x2aa7088,
    solo_param_repository_vmt: 0x2b9ab48,
    sprj_menu_man_ptr: 0x3d67408,
};
