use std::mem::MaybeUninit;
use std::ptr::NonNull;

use crate::cs::{CSInGamePad, CSKeyAssign, CSMenuViewerPad, CSPad};
use crate::dluid::InputDevices;
use crate::dlut::DLFixedVector;
use crate::{Pair, Tree};

use shared::{Subclass, Superclass};

/// Represents the Handle of a type. Generated by DLRF.
/// This is used in the [Tree<>] lookups for [CSPad] and [KeyAssign] instances as the Key value in the [Pair<>]s.
type RuntimeTypeHandle = usize;

const CAPACITY: usize = 4;

/// Structure that manages inputs from devices, a.e Controller, Keyboard and Mouse.
#[repr(C)]
#[shared::singleton("FD4PadManager")]
pub struct FD4PadManager {
    /// Copied over from the `Global_MainHeapAllocator`` when constructed.
    allocator: *const (),
    /// Copied over from [CSWindowImp] when constructed.
    pub window_handle: isize,
    unk10: *const (),
    /// List of `InputDevices` instances. Each `InputDevices` maps the button states from the connected devices.
    ///
    /// The game looks up a [CSPad] and then checks the [CSKeyAssign] before indexing the [VirtualMultiDevice] for the state of the buttons.
    pub input_devices_list: DLFixedVector<NonNull<InputDevices>, CAPACITY>,
    /// List of pairs holding various [CSPad] instances.
    ///
    /// The game looks up the [CSPad] with the [CSInGamePad_UserInput1Vmt] by it's [RuntimeTypeHandle].
    pub pad_list: DLFixedVector<NonNull<Tree<Pair<RuntimeTypeHandle, PadEntry>>>, CAPACITY>,
    /// Holds the key assignments used for mapping keys to specific codes used by the virtual devices.
    ///
    /// These are also referenced in [CSPad] instances. The [RuntimeTypeHandle] here matches that of the [CSPad] it's attached to.
    pub key_assign_list:
        DLFixedVector<NonNull<Tree<Pair<RuntimeTypeHandle, NonNull<CSKeyAssign>>>>, CAPACITY>,
    /// Contains pointers to the same struct as field 0x58 in the [CSKeyAssign] instances.
    unka8: DLFixedVector<NonNull<usize>, CAPACITY>,
    unkd8: *const (),
    /// List of the initialized [PadEntry] instances.
    ///
    /// When the [PadEntry] in the `pad_list` is created, it's gonna store a reference here.
    ///
    /// This list isn't ordered and isn't used for lookups.
    pub loaded_pad_entries: [MaybeUninit<NonNull<PadEntry>>; 9],
    unk128: DLFixedVector<usize, CAPACITY>,
    unk158: [u8; 0xC0],
    unk218: u64,
    heap_allocator: *const (),
    unk228: [u8; 0xC0],
    unk2e8: u64,
    unk2f0: u64,
    /// Trigger to set `is_back_ground_window` to true.
    ///
    /// Becomes `false` after triggering in the next frame.
    pub exit_foreground_signaled: bool,
    /// True when the game isn't a foreground window.
    ///
    /// Disables inputs from being read while true.
    ///
    /// Becomes `true` after the frame `exit_foreground_signaled` was set to `true`.
    pub is_back_ground_window: bool,
    unk2fa: bool,
    unk2fb: bool,
}

impl FD4PadManager {
    /// Obtains the specific [CSPad] responsible for regular in-game inputs.
    /// This is polled during the `InGameStep`.
    /// The rtti for this instance is `CSInGamePad_UserInput1`.
    pub fn get_in_game_pad(&self) -> Option<&mut CSInGamePad> {
        self.get_pad_instance::<CSInGamePad>()
    }

    pub fn get_menu_viewer_pad(&self) -> Option<&mut CSMenuViewerPad> {
        self.get_pad_instance::<CSMenuViewerPad>()
    }

    fn get_pad_instance<T: Subclass<CSPad>>(&self) -> Option<&mut T> {
        self.pad_list
            .iter()
            .find_map(|tree: &NonNull<Tree<Pair<usize, PadEntry>>>| {
                let tree: &Tree<Pair<usize, PadEntry>> = unsafe { tree.as_ref() };
                tree.iter().find_map(|pair: &mut Pair<usize, PadEntry>| {
                    let cs_pad: &mut CSPad = unsafe { pair.value.entry.as_mut() };
                    cs_pad.as_subclass_mut::<T>()
                })
            })
    }
}

#[repr(C)]
pub struct PadEntry {
    /// Pointer to it's [CSPad] subclass.
    pub entry: NonNull<CSPad>,
    /// Setting this to `true` enables you to read inputs using this [CSPad] instance.
    pub enable_use: bool,
}
