name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  RUSTDOCFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        run: |
          rustup target remove x86_64-pc-windows-gnu
          rustup target remove i686-pc-windows-msvc
          rustup toolchain install stable `
            --target x86_64-pc-windows-msvc `
            --component clippy,rustfmt `
            --profile minimal `
            --no-self-update
          rustup default stable

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-workspace-crates: "true"

      - name: Formatting
        run: cargo fmt -- --check

      - name: Build
        run: cargo build --tests --profile ci  --verbose

      - name: Tests
        run: cargo test --profile ci --lib --tests --bins --verbose

      - name: Clippy
        run: cargo clippy --profile ci --all-targets --no-deps

      - name: Documentation
        run: cargo doc --no-deps
