name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings --cfg windows_raw_dylib"
  RUSTDOCFLAGS: "-Dwarnings"
  CARGO_TARGET_X86_64_PC_WINDOWS_GNU_RUNNER: wine64
  CARGO_BUILD_TARGET: x86_64-pc-windows-gnu

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WINEDEBUG: "-all"
      WINEDLLOVERRIDES: "mscoree,mshtml,winegstreamer,winevulkan="

    steps:
      - uses: actions/checkout@v6

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64-win32 wine64

      - name: Setup
        run: |
          sudo ln -sf /usr/lib/wine/wine64 /usr/local/bin/wine64
          sudo ln -sf /usr/bin/x86_64-w64-mingw32-gcc-win32 /usr/bin/x86_64-w64-mingw32-gcc
          rustup target add x86_64-pc-windows-gnu
          rustup component add clippy rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          cache-workspace-crates: "true"
          cache-bin: "false"

      - name: Formatting
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --profile ci --all-targets --no-deps

      - name: Documentation
        run: cargo doc --no-deps

      - name: Build
        run: cargo build --tests --profile ci --verbose

      - name: Tests
        run: cargo test --profile ci --lib --tests --bins --verbose
